# Generated by Django 5.0.2 on 2024-03-04 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ("-updated_at",),
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
    ]
